server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /status.js {
        try_files $uri =404;
    }

    location /incidents.js {
        try_files $uri =404;
    }

    location /incidents.json {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }
}